package io.github.broot5.komicinfo.model

import java.math.BigDecimal
import kotlinx.datetime.LocalDate

public data class ComicInfo(
    public val title: String? = null,
    public val series: String? = null,
    public val number: String? = null,
    public val count: Int? = null,
    public val volume: Int? = null,
    public val alternateSeries: String? = null,
    public val alternateNumber: String? = null,
    public val alternateCount: Int? = null,
    public val summary: String? = null,
    public val notes: String? = null,
    public val date: LocalDate? = null, // Year/Month/Day from ComicInfo XML
    public val writer: List<String> = emptyList(),
    public val penciller: List<String> = emptyList(),
    public val inker: List<String> = emptyList(),
    public val colorist: List<String> = emptyList(),
    public val letterer: List<String> = emptyList(),
    public val coverArtist: List<String> = emptyList(),
    public val editor: List<String> = emptyList(),
    public val translator: List<String> = emptyList(),
    public val publisher: String? = null,
    public val imprint: String? = null,
    public val genre: List<String> = emptyList(),
    public val tags: List<String> = emptyList(),
    public val web: List<String> = emptyList(),
    public val pageCount: Int = 0,
    public val languageISO: String? = null,
    public val format: String? = null,
    public val blackAndWhite: YesNo? = null,
    public val manga: Manga? = null,
    public val characters: List<String> = emptyList(),
    public val teams: List<String> = emptyList(),
    public val locations: List<String> = emptyList(),
    public val scanInformation: String? = null,
    public val storyArc: List<String> = emptyList(),
    public val storyArcNumber: List<String> = emptyList(),
    public val seriesGroup: List<String> = emptyList(),
    public val ageRating: AgeRating? = null,
    public val pages: List<ComicPage> = emptyList(),
    public val communityRating: BigDecimal? = null,
    public val mainCharacterOrTeam: String? = null,
    public val review: String? = null,
    public val gtin: String? = null,
)
