package io.github.broot5.komicinfo

import java.io.File
import javax.imageio.ImageIO

data class ComicBook(
    val info: ComicInfo,
    val imageFiles: List<File>,
) {
  companion object {
    fun create(
        baseInfo: ComicInfo,
        imageFiles: List<File>,
        pageBuilder: (page: ComicPage, file: File) -> ComicPage = { page, _ -> page },
    ): ComicBook {
      val pages =
          imageFiles.mapIndexed { index, file ->
            val dimensions =
                runCatching { ImageIO.read(file)?.let { Pair(it.width, it.height) } }
                    .onFailure { println("Couldn't read image dimensions from ${file.name}") }
                    .getOrNull()

            val autoGeneratedPage =
                ComicPage(
                    image = index,
                    imageSize = file.length(),
                    imageWidth = dimensions?.first,
                    imageHeight = dimensions?.second,
                )

            pageBuilder(autoGeneratedPage, file)
          }
      val finalInfo =
          baseInfo.copy(
              pageCount = imageFiles.size,
              pages = pages,
          )

      return ComicBook(info = finalInfo, imageFiles = imageFiles)
    }
  }
}
