package io.github.broot5.komicinfo

import io.github.broot5.komicinfo.model.ComicInfo
import io.github.broot5.komicinfo.model.ComicPage
import java.io.File
import javax.imageio.ImageIO

data class ComicBook(
    val info: ComicInfo,
    val imageFiles: List<File>,
) {
  companion object {
    /**
     * Creates a ComicBook with auto-generated page information.
     *
     * Automatically reads image dimensions and file sizes. Image reading failures are silently
     * ignored - dimensions will be null for failed images.
     *
     * @param baseInfo Base comic information
     * @param imageFiles List of image files in page order
     * @param pageBuilder Optional lambda to customize page information
     * @return A new ComicBook instance
     */
    fun create(
        baseInfo: ComicInfo,
        imageFiles: List<File>,
        pageBuilder: (page: ComicPage, file: File) -> ComicPage = { page, _ -> page },
    ): ComicBook {
      val pages =
          imageFiles.mapIndexed { index, file ->
            val dimensions =
                runCatching { ImageIO.read(file)?.let { Pair(it.width, it.height) } }.getOrNull()

            val autoGeneratedPage =
                ComicPage(
                    image = index,
                    imageSize = file.length().takeIf { it > 0 },
                    imageWidth = dimensions?.first,
                    imageHeight = dimensions?.second,
                )

            pageBuilder(autoGeneratedPage, file)
          }

      val finalInfo =
          baseInfo.copy(
              pageCount = imageFiles.size,
              pages = pages,
          )

      return ComicBook(info = finalInfo, imageFiles = imageFiles)
    }
  }
}
