package io.github.broot5.komicinfo

import io.github.broot5.komicinfo.internal.ImageDimensions
import io.github.broot5.komicinfo.model.ComicInfo
import io.github.broot5.komicinfo.model.ComicPage
import java.io.File

/** Comic metadata plus the ordered list of page images. */
data class ComicBook(
    val info: ComicInfo,
    val imageFiles: List<File>,
) {
  companion object {
    /**
     * Builds a comic, blending existing metadata with file-derived sizes and dimensions.
     *
     * @param baseInfo base ComicInfo used as a source for semantic per-page metadata
     * @param imageFiles page images in reading order
     * @param pageBuilder hook to tweak each merged page before it is stored
     */
    fun create(
        baseInfo: ComicInfo,
        imageFiles: List<File>,
        pageBuilder: (page: ComicPage, file: File) -> ComicPage = { page, _ -> page },
    ): ComicBook {
      val pages =
          imageFiles.mapIndexed { index, file ->
            val dimensions = ImageDimensions.read(file)

            val autoGeneratedPage =
                ComicPage(
                    image = index,
                    imageSize = file.length().takeIf { it > 0 },
                    imageWidth = dimensions?.first,
                    imageHeight = dimensions?.second,
                )

            val existingPage = baseInfo.pages.getOrNull(index)
            val mergedPage = mergePageMetadata(existingPage, autoGeneratedPage)

            pageBuilder(mergedPage, file)
          }

      val finalInfo =
          baseInfo.copy(
              pageCount = imageFiles.size,
              pages = pages,
          )

      return ComicBook(info = finalInfo, imageFiles = imageFiles)
    }
  }
}

/**
 * Merge page metadata from [existing] and [generated].
 *
 * Prefers user-provided semantic metadata, but prefers file-derived values (size/dimensions) when
 * they can be computed from the actual image file.
 */
private fun mergePageMetadata(existing: ComicPage?, generated: ComicPage): ComicPage {
  if (existing == null) return generated

  return ComicPage(
      image = generated.image,
      type = existing.type ?: generated.type,
      doublePage = existing.doublePage ?: generated.doublePage,
      imageSize = generated.imageSize ?: existing.imageSize,
      key = existing.key ?: generated.key,
      bookmark = existing.bookmark ?: generated.bookmark,
      imageWidth = generated.imageWidth ?: existing.imageWidth,
      imageHeight = generated.imageHeight ?: existing.imageHeight,
  )
}
